source 'https://github.com/CocoaPods/Specs.git'

target 'OmnyPayAPIDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'KVNProgress'
  pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream.git', :branch => 'swift3'

end


