source 'https://github.com/CocoaPods/Specs.git'

target 'OmnyPayDemoApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # pod 'Alamofire', '~> 3.5'
  pod 'KVNProgress'
  pod 'Starscream', '~> 1.1.3'
  # pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'swift2.3'

end
