source 'https://github.com/CocoaPods/Specs.git'
source 'http://mobile-sdk.jumio.com/distribution.git'

target 'OmnyPayAllSdkDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'KVNProgress'
  pod 'Starscream', '~> 1.1.4'
  pod 'JumioMobileSDK-FAT/Netverify', '2.3.1'

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3' # or '3.0'
    end
  end
end
