source 'https://github.com/CocoaPods/Specs.git'

# Include following line if OmnyPayIdentity SDK or OmnyPayPIScan SDK will be used
source 'http://mobile-sdk.jumio.com/distribution.git'

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'OmnyPayAllSdkDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'KVNProgress'
  
  # Mandatory pod while using OmnyPayAPI SDK
  pod 'Starscream'
  
  # Mandatory if using OmnyPayIdentity SDK
  pod 'JumioMobileSDK-FAT/Netverify', '2.3.1'
  
  # Mandatory if using OmnyPayPIScan SDK
  pod 'JumioMobileSDK-FAT/Netswipe', '2.3.1'

end





